// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSjJX50tjeGqxFW2KCs9z0xnQ284joZwI',
    appId: '1:760762236393:web:469a5903d867f6a8019f78',
    messagingSenderId: '760762236393',
    projectId: 'cerita-7bd27',
    authDomain: 'cerita-7bd27.firebaseapp.com',
    storageBucket: 'cerita-7bd27.appspot.com',
    measurementId: 'G-T5QKP5BXWE  ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ-eLuMdvSBj_t9Xs6RFaRWVoccut7q-Y',
    appId: '1:760762236393:android:84257dab6de8bdf3019f78',
    messagingSenderId: 'QySX0jsvQfKF5KGnB_D-qw',
    projectId: 'cerita-7bd27',
    storageBucket: 'cerita-7bd27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbWrNZwfUrbL3NzLoFj2wmr7gv6EIJyJY',
    appId: '1:760762236393:ios:b6064a3ae174a1bc019f78',
    messagingSenderId: '760762236393',
    projectId: 'cerita-7bd27',
    storageBucket: 'cerita-7bd27.appspot.com',
    iosClientId: '760762236393-rh87jbikh8c932kpvde7egqu6qpi6eom.apps.googleusercontent.com',
    iosBundleId: 'com.example.ceritayuk',
  );
}
